<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InterestsTableSeeder extends Seeder
{
    public function run(): void
    {

        $interests = [
            ['title' => 'Sports', 'icon' => 'interests/1.png'],
            ['title' => 'Music', 'icon' => 'interests/2.png'],
            ['title' => 'Reading', 'icon' => 'interests/3.png'],
            ['title' => 'Travel', 'icon' => 'interests/4.png'],
            ['title' => 'Cooking', 'icon' => 'interests/5.png'],
            ['title' => 'Video Games', 'icon' => 'interests/6.png'],
            ['title' => 'Photography', 'icon' => 'interests/7.png'],
            ['title' => 'Movies', 'icon' => 'interests/8.png'],
            ['title' => 'Technology', 'icon' => 'interests/9.png'],
            ['title' => 'Shopping', 'icon' => 'interests/10.png'],
            ['title' => 'Art', 'icon' => 'interests/11.png'],
            ['title' => 'Writing', 'icon' => 'interests/12.png'],
            ['title' => 'Fitness', 'icon' => 'interests/13.png'],
            ['title' => 'Hiking', 'icon' => 'interests/14.png'],
            ['title' => 'Cycling', 'icon' => 'interests/15.png'],
            ['title' => 'Swimming', 'icon' => 'interests/16.png'],
            ['title' => 'Dancing', 'icon' => 'interests/17.png'],
            ['title' => 'Fashion', 'icon' => 'interests/18.png'],
            ['title' => 'Gardening', 'icon' => 'interests/19.png'],
            ['title' => 'Volunteering', 'icon' => 'interests/20.png'],
            ['title' => 'Yoga', 'icon' => 'interests/21.png'],
            ['title' => 'Meditation', 'icon' => 'interests/22.png'],
            ['title' => 'Painting', 'icon' => 'interests/23.png'],
            ['title' => 'Drawing', 'icon' => 'interests/24.png'],
            ['title' => 'Sculpting', 'icon' => 'interests/25.png'],
            ['title' => 'Knitting', 'icon' => 'interests/26.png'],
            ['title' => 'Crochet', 'icon' => 'interests/27.png'],
            ['title' => 'Sewing', 'icon' => 'interests/28.png'],
            ['title' => 'Woodworking', 'icon' => 'interests/29.png'],
            ['title' => 'Pottery', 'icon' => 'interests/30.png'],
            ['title' => 'Collecting', 'icon' => 'interests/31.png'],
            ['title' => 'Board Games', 'icon' => 'interests/32.png'],
            ['title' => 'Puzzles', 'icon' => 'interests/33.png'],
            ['title' => 'Chess', 'icon' => 'interests/34.png'],
            ['title' => 'Running', 'icon' => 'interests/35.png'],
            ['title' => 'Marathon', 'icon' => 'interests/36.png'],
            ['title' => 'Tennis', 'icon' => 'interests/37.png'],
            ['title' => 'Basketball', 'icon' => 'interests/38.png'],
            ['title' => 'Football', 'icon' => 'interests/39.png'],
            ['title' => 'Soccer', 'icon' => 'interests/40.png'],
            ['title' => 'Golf', 'icon' => 'interests/41.png'],
            ['title' => 'Baseball', 'icon' => 'interests/42.png'],
            ['title' => 'Surfing', 'icon' => 'interests/43.png'],
            ['title' => 'Skiing', 'icon' => 'interests/44.png'],
            ['title' => 'Snowboarding', 'icon' => 'interests/45.png'],
            ['title' => 'Rock Climbing', 'icon' => 'interests/46.png'],
            ['title' => 'Camping', 'icon' => 'interests/47.png'],
            ['title' => 'Fishing', 'icon' => 'interests/48.png'],
            ['title' => 'Hunting', 'icon' => 'interests/49.png'],
            ['title' => 'Bird Watching', 'icon' => 'interests/50.png'],
            ['title' => 'Astronomy', 'icon' => 'interests/51.png'],
            ['title' => 'Stargazing', 'icon' => 'interests/52.png'],
            ['title' => 'Comics', 'icon' => 'interests/53.png'],
            ['title' => 'Anime', 'icon' => 'interests/54.png'],
            ['title' => 'Manga', 'icon' => 'interests/55.png'],
            ['title' => 'Theater', 'icon' => 'interests/56.png'],
            ['title' => 'Comedy', 'icon' => 'interests/57.png'],
            ['title' => 'Stand-up', 'icon' => 'interests/58.png'],
            ['title' => 'Podcasts', 'icon' => 'interests/59.png'],
            ['title' => 'Audiobooks', 'icon' => 'interests/60.png'],
            ['title' => 'Learning Languages', 'icon' => 'interests/61.png'],
            ['title' => 'History', 'icon' => 'interests/62.png'],
            ['title' => 'Science', 'icon' => 'interests/63.png'],
            ['title' => 'Mathematics', 'icon' => 'interests/64.png'],
            ['title' => 'Philosophy', 'icon' => 'interests/65.png'],
            ['title' => 'Psychology', 'icon' => 'interests/66.png'],
            ['title' => 'Crafts', 'icon' => 'interests/67.png'],
            ['title' => 'DIY Projects', 'icon' => 'interests/68.png'],
            ['title' => 'Home Decor', 'icon' => 'interests/69.png'],
            ['title' => 'Interior Design', 'icon' => 'interests/70.png'],
            ['title' => 'Beauty', 'icon' => 'interests/71.png'],
            ['title' => 'Makeup', 'icon' => 'interests/72.png'],
            ['title' => 'Skincare', 'icon' => 'interests/73.png'],
            ['title' => 'Wellness', 'icon' => 'interests/74.png'],
            ['title' => 'Nutrition', 'icon' => 'interests/75.png'],
            ['title' => 'Healthy Living', 'icon' => 'interests/76.png'],
            ['title' => 'Veganism', 'icon' => 'interests/77.png'],
            ['title' => 'Vegetarianism', 'icon' => 'interests/78.png'],
            ['title' => 'Baking', 'icon' => 'interests/79.png'],
            ['title' => 'Wine Tasting', 'icon' => 'interests/80.png'],
            ['title' => 'Coffee', 'icon' => 'interests/81.png'],
            ['title' => 'Tea', 'icon' => 'interests/82.png'],
            ['title' => 'Cocktails', 'icon' => 'interests/83.png'],
            ['title' => 'Mixology', 'icon' => 'interests/84.png'],
            ['title' => 'Cars', 'icon' => 'interests/85.png'],
            ['title' => 'Motorcycles', 'icon' => 'interests/86.png'],
            ['title' => 'Aviation', 'icon' => 'interests/87.png'],
            ['title' => 'Drones', 'icon' => 'interests/88.png'],
            ['title' => 'Robotics', 'icon' => 'interests/89.png'],
            ['title' => '3D Printing', 'icon' => 'interests/90.png'],
            ['title' => 'Cryptocurrency', 'icon' => 'interests/91.png'],
            ['title' => 'Investing', 'icon' => 'interests/91.png'],
            ['title' => 'Trading', 'icon' => 'interests/93.png'],
            ['title' => 'Business', 'icon' => 'interests/94.png'],
            ['title' => 'Entrepreneurship', 'icon' => 'interests/95.png'],
            ['title' => 'Pets', 'icon' => 'interests/96.png'],
            ['title' => 'Dogs', 'icon' => 'interests/97.png'],
            ['title' => 'Cats', 'icon' => 'interests/98.png'],
            ['title' => 'Horses', 'icon' => 'interests/99.png'],
            ['title' => 'Reptiles', 'icon' => 'interests/100.png'],
            ['title' => 'Aquariums', 'icon' => 'interests/101.png'],
            ['title' => 'Magic', 'icon' => 'interests/102.png'],
            ['title' => 'Juggling', 'icon' => 'interests/103.png'],
            ['title' => 'Circus Arts', 'icon' => 'interests/104.png'],
            ['title' => 'Parkour', 'icon' => 'interests/105.png'],
            ['title' => 'Martial Arts', 'icon' => 'interests/106.png'],
            ['title' => 'Karate', 'icon' => 'interests/107.png'],
            ['title' => 'Judo', 'icon' => 'interests/108.png'],
            ['title' => 'Boxing', 'icon' => 'interests/109.png'],
            ['title' => 'Wrestling', 'icon' => 'interests/110.png'],
            ['title' => 'Pilates', 'icon' => 'interests/111.png'],
            ['title' => 'CrossFit', 'icon' => 'interests/112.png'],
            ['title' => 'Weightlifting', 'icon' => 'interests/113.png'],
            ['title' => 'Bodybuilding', 'icon' => 'interests/114.png'],
            ['title' => 'Gymnastics', 'icon' => 'interests/115.png'],
            ['title' => 'Acrobatics', 'icon' => 'interests/116.png'],
            ['title' => 'Skateboarding', 'icon' => 'interests/117.png'],
            ['title' => 'Rollerblading', 'icon' => 'interests/118.png'],
            ['title' => 'Ice Skating', 'icon' => 'interests/119.png'],
        ];

        foreach ($interests as $interest) {
            DB::table('interests')->insert([
                'title' => $interest['title'],
                'icon' => $interest['icon'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
