<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InterestsTableSeeder extends Seeder
{
    public function run(): void
    {

        $interests = [
            ['title' => 'Sports', 'icon' => 'interests/1.png', 'keywords' => 'sports athletics games competition team exercise fitness physical activity'],
            ['title' => 'Music', 'icon' => 'interests/2.png', 'keywords' => 'music songs melody rhythm beats instruments concerts bands musicians'],
            ['title' => 'Reading', 'icon' => 'interests/3.png', 'keywords' => 'reading books novels literature stories authors pages library'],
            ['title' => 'Travel', 'icon' => 'interests/4.png', 'keywords' => 'travel journey trip vacation adventure explore destinations tourism'],
            ['title' => 'Cooking', 'icon' => 'interests/5.png', 'keywords' => 'cooking recipes food cuisine kitchen chef meals dishes'],
            ['title' => 'Video Games', 'icon' => 'interests/6.png', 'keywords' => 'video games gaming console playstation xbox nintendo pc gaming'],
            ['title' => 'Photography', 'icon' => 'interests/7.png', 'keywords' => 'photography photos pictures camera lens shots images capture'],
            ['title' => 'Movies', 'icon' => 'interests/8.png', 'keywords' => 'movies films cinema theater actors directors entertainment'],
            ['title' => 'Technology', 'icon' => 'interests/9.png', 'keywords' => 'technology tech gadgets devices computers software innovation digital'],
            ['title' => 'Shopping', 'icon' => 'interests/10.png', 'keywords' => 'shopping retail stores malls fashion clothes accessories'],
            ['title' => 'Art', 'icon' => 'interests/11.png', 'keywords' => 'art painting drawing creative artistic gallery museum visual'],
            ['title' => 'Writing', 'icon' => 'interests/12.png', 'keywords' => 'writing author stories novels poetry blog articles'],
            ['title' => 'Fitness', 'icon' => 'interests/13.png', 'keywords' => 'fitness workout exercise gym health training strength'],
            ['title' => 'Hiking', 'icon' => 'interests/14.png', 'keywords' => 'hiking trails mountains nature walking outdoor adventure'],
            ['title' => 'Cycling', 'icon' => 'interests/15.png', 'keywords' => 'cycling bike bicycle riding road mountain biking'],
            ['title' => 'Swimming', 'icon' => 'interests/16.png', 'keywords' => 'swimming pool water aquatic exercise laps'],
            ['title' => 'Dancing', 'icon' => 'interests/17.png', 'keywords' => 'dancing dance moves rhythm music choreography performance'],
            ['title' => 'Fashion', 'icon' => 'interests/18.png', 'keywords' => 'fashion style clothes clothing trends designer outfits'],
            ['title' => 'Gardening', 'icon' => 'interests/19.png', 'keywords' => 'gardening plants flowers vegetables garden soil planting'],
            ['title' => 'Volunteering', 'icon' => 'interests/20.png', 'keywords' => 'volunteering charity help community service giving back'],
            ['title' => 'Yoga', 'icon' => 'interests/21.png', 'keywords' => 'yoga meditation stretching flexibility mindfulness relaxation'],
            ['title' => 'Meditation', 'icon' => 'interests/22.png', 'keywords' => 'meditation mindfulness peace calm relaxation zen breathing'],
            ['title' => 'Painting', 'icon' => 'interests/23.png', 'keywords' => 'painting canvas brushes colors art acrylic oil watercolor'],
            ['title' => 'Drawing', 'icon' => 'interests/24.png', 'keywords' => 'drawing sketch pencil pen illustration art design'],
            ['title' => 'Sculpting', 'icon' => 'interests/25.png', 'keywords' => 'sculpting sculpture clay stone carving art 3d'],
            ['title' => 'Knitting', 'icon' => 'interests/26.png', 'keywords' => 'knitting yarn needles wool scarf sweater craft'],
            ['title' => 'Crochet', 'icon' => 'interests/27.png', 'keywords' => 'crochet hook yarn thread pattern blanket craft'],
            ['title' => 'Sewing', 'icon' => 'interests/28.png', 'keywords' => 'sewing needle thread fabric clothes patterns tailoring'],
            ['title' => 'Woodworking', 'icon' => 'interests/29.png', 'keywords' => 'woodworking carpentry wood tools furniture building craft'],
            ['title' => 'Pottery', 'icon' => 'interests/30.png', 'keywords' => 'pottery clay ceramic wheel glazing firing art'],
            ['title' => 'Collecting', 'icon' => 'interests/31.png', 'keywords' => 'collecting collection items collectibles antiques stamps coins'],
            ['title' => 'Board Games', 'icon' => 'interests/32.png', 'keywords' => 'board games strategy cards monopoly chess family fun'],
            ['title' => 'Puzzles', 'icon' => 'interests/33.png', 'keywords' => 'puzzles jigsaw crossword sudoku brain games challenge'],
            ['title' => 'Chess', 'icon' => 'interests/34.png', 'keywords' => 'chess strategy game pieces board checkmate tournament'],
            ['title' => 'Running', 'icon' => 'interests/35.png', 'keywords' => 'running jogging marathon track race exercise cardio'],
            ['title' => 'Marathon', 'icon' => 'interests/36.png', 'keywords' => 'marathon running race long distance training endurance'],
            ['title' => 'Tennis', 'icon' => 'interests/37.png', 'keywords' => 'tennis racket court match serve volley tournament'],
            ['title' => 'Basketball', 'icon' => 'interests/38.png', 'keywords' => 'basketball hoop court team NBA game shooting'],
            ['title' => 'Football', 'icon' => 'interests/39.png', 'keywords' => 'football american NFL team touchdown game field'],
            ['title' => 'Soccer', 'icon' => 'interests/40.png', 'keywords' => 'soccer football field goal team match world cup'],
            ['title' => 'Golf', 'icon' => 'interests/41.png', 'keywords' => 'golf course club ball hole putt tournament'],
            ['title' => 'Baseball', 'icon' => 'interests/42.png', 'keywords' => 'baseball bat ball field team home run'],
            ['title' => 'Surfing', 'icon' => 'interests/43.png', 'keywords' => 'surfing waves ocean board beach water sport'],
            ['title' => 'Skiing', 'icon' => 'interests/44.png', 'keywords' => 'skiing snow slopes mountain winter sport alpine'],
            ['title' => 'Snowboarding', 'icon' => 'interests/45.png', 'keywords' => 'snowboarding snow board mountain slopes winter'],
            ['title' => 'Rock Climbing', 'icon' => 'interests/46.png', 'keywords' => 'rock climbing mountain wall ropes gear adventure'],
            ['title' => 'Camping', 'icon' => 'interests/47.png', 'keywords' => 'camping tent outdoor nature fire marshmallows adventure'],
            ['title' => 'Fishing', 'icon' => 'interests/48.png', 'keywords' => 'fishing rod reel bait water catch fish'],
            ['title' => 'Hunting', 'icon' => 'interests/49.png', 'keywords' => 'hunting game wildlife outdoor nature adventure'],
            ['title' => 'Bird Watching', 'icon' => 'interests/50.png', 'keywords' => 'bird watching birds nature wildlife observation binoculars'],
            ['title' => 'Astronomy', 'icon' => 'interests/51.png', 'keywords' => 'astronomy stars planets space telescope universe science'],
            ['title' => 'Stargazing', 'icon' => 'interests/52.png', 'keywords' => 'stargazing stars night sky telescope constellation'],
            ['title' => 'Comics', 'icon' => 'interests/53.png', 'keywords' => 'comics graphic novels superheroes manga reading'],
            ['title' => 'Anime', 'icon' => 'interests/54.png', 'keywords' => 'anime japanese animation series manga watching'],
            ['title' => 'Manga', 'icon' => 'interests/55.png', 'keywords' => 'manga japanese comics reading books graphic novels'],
            ['title' => 'Theater', 'icon' => 'interests/56.png', 'keywords' => 'theater drama plays acting stage performance'],
            ['title' => 'Comedy', 'icon' => 'interests/57.png', 'keywords' => 'comedy humor jokes funny stand-up laughter'],
            ['title' => 'Stand-up', 'icon' => 'interests/58.png', 'keywords' => 'stand-up comedy jokes performance mic stage'],
            ['title' => 'Podcasts', 'icon' => 'interests/59.png', 'keywords' => 'podcasts audio listening shows episodes talk'],
            ['title' => 'Audiobooks', 'icon' => 'interests/60.png', 'keywords' => 'audiobooks listening books audio narration'],
            ['title' => 'Learning Languages', 'icon' => 'interests/61.png', 'keywords' => 'languages learning foreign language study communication'],
            ['title' => 'History', 'icon' => 'interests/62.png', 'keywords' => 'history past events historical facts ancient'],
            ['title' => 'Science', 'icon' => 'interests/63.png', 'keywords' => 'science research experiments physics chemistry biology'],
            ['title' => 'Mathematics', 'icon' => 'interests/64.png', 'keywords' => 'mathematics math numbers equations algebra calculus'],
            ['title' => 'Philosophy', 'icon' => 'interests/65.png', 'keywords' => 'philosophy thinking wisdom ethics logic ideas'],
            ['title' => 'Psychology', 'icon' => 'interests/66.png', 'keywords' => 'psychology mind behavior mental health study'],
            ['title' => 'Crafts', 'icon' => 'interests/67.png', 'keywords' => 'crafts handmade DIY creative projects making'],
            ['title' => 'DIY Projects', 'icon' => 'interests/68.png', 'keywords' => 'DIY do it yourself projects building making'],
            ['title' => 'Home Decor', 'icon' => 'interests/69.png', 'keywords' => 'home decor interior design furniture decoration'],
            ['title' => 'Interior Design', 'icon' => 'interests/70.png', 'keywords' => 'interior design decoration home style furniture'],
            ['title' => 'Beauty', 'icon' => 'interests/71.png', 'keywords' => 'beauty cosmetics skincare makeup grooming'],
            ['title' => 'Makeup', 'icon' => 'interests/72.png', 'keywords' => 'makeup cosmetics beauty products application'],
            ['title' => 'Skincare', 'icon' => 'interests/73.png', 'keywords' => 'skincare beauty routine face care products'],
            ['title' => 'Wellness', 'icon' => 'interests/74.png', 'keywords' => 'wellness health self-care mindfulness balance'],
            ['title' => 'Nutrition', 'icon' => 'interests/75.png', 'keywords' => 'nutrition diet food healthy eating vitamins'],
            ['title' => 'Healthy Living', 'icon' => 'interests/76.png', 'keywords' => 'healthy living wellness fitness diet lifestyle'],
            ['title' => 'Veganism', 'icon' => 'interests/77.png', 'keywords' => 'veganism vegan plant-based diet no animal products'],
            ['title' => 'Vegetarianism', 'icon' => 'interests/78.png', 'keywords' => 'vegetarianism vegetarian plant-based diet no meat'],
            ['title' => 'Baking', 'icon' => 'interests/79.png', 'keywords' => 'baking cakes cookies bread pastries oven'],
            ['title' => 'Wine Tasting', 'icon' => 'interests/80.png', 'keywords' => 'wine tasting vino grapes sommelier bottles'],
            ['title' => 'Coffee', 'icon' => 'interests/81.png', 'keywords' => 'coffee espresso latte cappuccino beans brew'],
            ['title' => 'Tea', 'icon' => 'interests/82.png', 'keywords' => 'tea leaves brew hot drink herbal'],
            ['title' => 'Cocktails', 'icon' => 'interests/83.png', 'keywords' => 'cocktails drinks mixology bar alcohol'],
            ['title' => 'Mixology', 'icon' => 'interests/84.png', 'keywords' => 'mixology cocktails drinks bartending recipes'],
            ['title' => 'Cars', 'icon' => 'interests/85.png', 'keywords' => 'cars automobiles vehicles driving auto mechanics'],
            ['title' => 'Motorcycles', 'icon' => 'interests/86.png', 'keywords' => 'motorcycles bikes riding motorcycle bikes'],
            ['title' => 'Aviation', 'icon' => 'interests/87.png', 'keywords' => 'aviation airplanes flying aircraft pilot'],
            ['title' => 'Drones', 'icon' => 'interests/88.png', 'keywords' => 'drones flying remote control quadcopter aerial'],
            ['title' => 'Robotics', 'icon' => 'interests/89.png', 'keywords' => 'robotics robots automation technology engineering'],
            ['title' => '3D Printing', 'icon' => 'interests/90.png', 'keywords' => '3D printing printer technology design models'],
            ['title' => 'Cryptocurrency', 'icon' => 'interests/91.png', 'keywords' => 'cryptocurrency bitcoin crypto blockchain digital currency'],
            ['title' => 'Investing', 'icon' => 'interests/91.png', 'keywords' => 'investing stocks finance money portfolio trading'],
            ['title' => 'Trading', 'icon' => 'interests/93.png', 'keywords' => 'trading stocks forex market finance investment'],
            ['title' => 'Business', 'icon' => 'interests/94.png', 'keywords' => 'business entrepreneurship commerce company management'],
            ['title' => 'Entrepreneurship', 'icon' => 'interests/95.png', 'keywords' => 'entrepreneurship business startup innovation company'],
            ['title' => 'Pets', 'icon' => 'interests/96.png', 'keywords' => 'pets animals dogs cats companions'],
            ['title' => 'Dogs', 'icon' => 'interests/97.png', 'keywords' => 'dogs puppies pets canine companions'],
            ['title' => 'Cats', 'icon' => 'interests/98.png', 'keywords' => 'cats kittens pets feline companions'],
            ['title' => 'Horses', 'icon' => 'interests/99.png', 'keywords' => 'horses equestrian riding animals'],
            ['title' => 'Reptiles', 'icon' => 'interests/100.png', 'keywords' => 'reptiles snakes lizards turtles pets'],
            ['title' => 'Aquariums', 'icon' => 'interests/101.png', 'keywords' => 'aquariums fish tanks water marine'],
            ['title' => 'Magic', 'icon' => 'interests/102.png', 'keywords' => 'magic tricks illusions performance magic show'],
            ['title' => 'Juggling', 'icon' => 'interests/103.png', 'keywords' => 'juggling balls tricks performance skill'],
            ['title' => 'Circus Arts', 'icon' => 'interests/104.png', 'keywords' => 'circus arts performance acrobatics entertainment'],
            ['title' => 'Parkour', 'icon' => 'interests/105.png', 'keywords' => 'parkour movement running jumping obstacles'],
            ['title' => 'Martial Arts', 'icon' => 'interests/106.png', 'keywords' => 'martial arts karate judo taekwondo fighting'],
            ['title' => 'Karate', 'icon' => 'interests/107.png', 'keywords' => 'karate martial arts fighting discipline training'],
            ['title' => 'Judo', 'icon' => 'interests/108.png', 'keywords' => 'judo martial arts grappling throwing'],
            ['title' => 'Boxing', 'icon' => 'interests/109.png', 'keywords' => 'boxing fighting gloves ring training'],
            ['title' => 'Wrestling', 'icon' => 'interests/110.png', 'keywords' => 'wrestling grappling fighting sport competition'],
            ['title' => 'Pilates', 'icon' => 'interests/111.png', 'keywords' => 'pilates exercise core strength flexibility'],
            ['title' => 'CrossFit', 'icon' => 'interests/112.png', 'keywords' => 'crossfit workout fitness training intense'],
            ['title' => 'Weightlifting', 'icon' => 'interests/113.png', 'keywords' => 'weightlifting weights gym strength training'],
            ['title' => 'Bodybuilding', 'icon' => 'interests/114.png', 'keywords' => 'bodybuilding muscles fitness training physique'],
            ['title' => 'Gymnastics', 'icon' => 'interests/115.png', 'keywords' => 'gymnastics flexibility acrobatics balance training'],
            ['title' => 'Acrobatics', 'icon' => 'interests/116.png', 'keywords' => 'acrobatics gymnastics tumbling performance'],
            ['title' => 'Skateboarding', 'icon' => 'interests/117.png', 'keywords' => 'skateboarding skateboard tricks ramps street'],
            ['title' => 'Rollerblading', 'icon' => 'interests/118.png', 'keywords' => 'rollerblading inline skating wheels'],
            ['title' => 'Ice Skating', 'icon' => 'interests/119.png', 'keywords' => 'ice skating rink winter sport blades'],
        ];

        foreach ($interests as $interest) {
            DB::table('interests')->updateOrInsert(
                [
                    'title' => $interest['title'],
                    'user_id' => null, // Only update/insert default interests
                ],
                [
                    'icon' => $interest['icon'],
                    'keywords' => $interest['keywords'],
                    'updated_at' => now(),
                    'created_at' => DB::raw('COALESCE(created_at, NOW())'), // Preserve existing created_at
                ]
            );
        }
    }
}
